# Site settings
title: 联极科技有限公司
email: lianji@gmail.com
description: "互联网时代新的工作方式"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503 
  secondary-dark: 000

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://github.com/LinkingEndless
  - title: github
    url: https://github.com/LinkingEndless
  - title: envelope
    url: mailto:lianji@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: 上海市
  - line: 浦东新区万祥镇宏祥北路83弄1-42号20幢

# Build settings
markdown: kramdown
permalink: pretty
